version: "3"
volumes:
  data:
services:
  web:
    build: .
    ports:
      - "3000:3000"
    #command: bundle exec rails s -p 3000 -b 0.0.0.0
    volumes:
      - ".:/code"
    tty: true
    stdin_open: true
    environment:
      - "DATABASE_PASSWORD=password"
    depends_on:
      - db
    links:
      - db
  db:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - "data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password
